services:
  db:
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "--dbname=${POSTGRES_DB}", "--username=${POSTGRES_USER}" ]
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 4m30s
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data

  cache:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  preloader:
    build: .
    command: bash -c "alembic upgrade head"
    restart: on-failure
    healthcheck:
      test: "netstat -plutn | grep 0.0.0.0:8000"
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 4m
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./src:/code"
    env_file:
      - "./.env"

  svc:
    build: .
    command: sh -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      preloader:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    volumes:
      - "./src:/code"
    env_file:
      - "./.env"

volumes:
  dbdata:
  redis_data:
